sudo: false
language: cpp
git:
  submodules: false
compiler:
- g++
- clang++
install:
- git submodule update --init
- make -C libsksat
- sed -i -e "s/gcc/gcc-5/g" common.mk
- sed -i -e "s/g++/g++-5/g" common.mk
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - llvm-toolchain-precise
    packages:
    - gcc-5
    - g++-5
    - clang-3.7
script:
- g++ --version
- make full
